spring:
  rabbitmq:
    host: 192.168.1.177
    port: 5672
    username: admin
    password: admin
  datasource:
     url: jdbc:mysql://192.168.1.237:3306/bd_dataharbour_tender?characterEncoding=UTF-8
     username: dataharbour
     password: dataharbour
     driver-class-name: com.mysql.jdbc.Driver
  redis:
     database: 0
     host: 192.168.1.230
     port: 6379
     password: 123456
     pool:
       max-active: 0
       max-wait: -1
       max-idle: 8
       min-idle: 0
     timeout: 0
  application:
     name: loadbalancing
  cloud:
     config:
       discovery:
         enabled: true
         serviceId: nodecloud
     refresh:
      refreshable: none
mybatis:
  mapper-locations: classpath:mapper/*.xml
fdfs:
  so-timeout: 1501
  connect-timeout: 601 
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.1.230:22222
  pool:
    #从池中借出的对象的最大数目
    max-total: 153
    #获取连接时的最大等待毫秒数100
    max-wait-millis: 102
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.232:8080/eureka/
    healthcheck:
      enabled: false
    instance:
      appname: loadbalancing
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
zuul:
  rotues:
    matchnode: /demo/**
ribbon:
  eureka:
    enabled: false
  ReadTimeout: 60000
  ConnectTimeout: 60000
  listOfServers: http://192.168.1.232:8080
